 # Pixi kommandon

 pixi init projekt_namn
 
 pixi add python jupyterlab pandas
 
 pixi run jupyter lab

In [1]:
name = "Susan"
print(name)

Susan

In [2]:
full_name = name + " Svensson"

In [3]:
print(full_name)

Susan Svensson

In [4]:
import pandas as pd

In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

iris_df = pd.read_csv(url, names=column_names)

In [6]:
iris_df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [7]:
iris_df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
mean_speal_lenth = iris_df['sepal_length'].mean()
print(mean_speal_lenth)

5.843333333333334

In [9]:
max_speal_lenth = iris_df['sepal_length'].max()
print(max_speal_lenth)

7.9

In [10]:
mean_per_speciies = iris_df.groupby('species').mean()
mean_per_speciies

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [11]:
filtered_df = iris_df[iris_df['petal_length'] > 3.0]

In [12]:
filtered_df.head()

    sepal_length  sepal_width  petal_length  petal_width          species
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor

In [13]:
filtered_df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count     99.000000    99.000000     99.000000    99.000000
mean       6.273737     2.875758      4.925253     1.681818
std        0.655679     0.332305      0.806902     0.422906
min        4.900000     2.000000      3.300000     1.000000
25%        5.800000     2.700000      4.400000     1.300000
50%        6.300000     2.900000      4.900000     1.600000
75%        6.700000     3.050000      5.550000     2.000000
max        7.900000     3.800000      6.900000     2.500000

In [16]:
multi_filter = iris_df[(iris_df['petal_length'] > 3.0) & (iris_df['petal_width'] < 2.0 )]
multi_filter

     sepal_length  sepal_width  petal_length  petal_width          species
50            7.0          3.2           4.7          1.4  Iris-versicolor
51            6.4          3.2           4.5          1.5  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
53            5.5          2.3           4.0          1.3  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
..            ...          ...           ...          ...              ...
137           6.4          3.1           5.5          1.8   Iris-virginica
138           6.0          3.0           4.8          1.8   Iris-virginica
142           5.8          2.7           5.1          1.9   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[70 rows x 5 columns]

In [17]:
# loc
#iloc
loc_selection = iris_df.loc[0:5, ['species', 'petal_length']]
loc_selection

       species  petal_length
0  Iris-setosa           1.4
1  Iris-setosa           1.4
2  Iris-setosa           1.3
3  Iris-setosa           1.5
4  Iris-setosa           1.4
5  Iris-setosa           1.7

In [18]:
iloc_selection = iris_df.iloc[0:5, 0:4]

In [19]:
iloc_selection

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [20]:
iris_df['petal_ratio'] = iris_df['petal_length'] / iris_df['petal_width']

In [21]:
iris_df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_ratio
0,5.1,3.5,1.4,0.2,Iris-setosa,7.0
1,4.9,3.0,1.4,0.2,Iris-setosa,7.0
2,4.7,3.2,1.3,0.2,Iris-setosa,6.5
3,4.6,3.1,1.5,0.2,Iris-setosa,7.5
4,5.0,3.6,1.4,0.2,Iris-setosa,7.0

In [23]:
iris_df['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64