In [1]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd

# Set the path to the file you'd like to load
file_path = "Social_media_impact_on_life.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "harishyadav0506/impact-of-social-media-on-life",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df.head()

/Users/david/jupyter-intro/.pixi/envs/default/lib/python3.15/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial

# verkar inte finnas något samband mellan primär plattform och antal timmar användning

In [2]:
mean_usage_by_gender = df.groupby('Gender')['Daily_Usage_Hours'].mean()
mean_usage_by_gender

Gender
Female               5.324440
Male                 5.255924
Non-Binary           5.395902
Prefer not to say    5.362366
Name: Daily_Usage_Hours, dtype: float64

In [3]:
cols = ['Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Perceived_Stress_Score' ]

df.groupby('Late_Night_Usage')[cols].mean()

,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score
Late_Night_Usage,,,
False,7.085884,2.807112,11.162955
True,6.431392,2.236762,15.167241

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   str
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   str
 3   Academic_Level               4500 non-null   str
 4   Primary_Platform             4500 non-null   str
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   str
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   str
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   str
dtypes: bool(1), float64(5), int64(3), str(7)
memory usage: 531.9 KB

In [5]:
df['Primary_Platform'].value_counts()

Primary_Platform
Instagram      1453
TikTok         1226
YouTube         818
Snapchat        472
Reddit          229
X (Twitter)     206
LinkedIn         96
Name: count, dtype: int64

In [6]:
df['Overall_Impact'].value_counts()

Overall_Impact
Beneficial    3681
Neutral        654
Negative       165
Name: count, dtype: int64

In [7]:
df.isna().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Primary_Platform                0
Daily_Usage_Hours               0
Weekend_Extra_Hours             0
Device_Type                     0
Sleep_Duration_Hours            0
Sleep_Quality_Score             0
Late_Night_Usage                0
Social_Comparison_Frequency     0
Perceived_Stress_Score         46
Mental_Health_Index             0
Academic_Performance_GPA       85
Overall_Impact                  0
dtype: int64

In [8]:
df_clean = df.dropna(subset=['Perceived_Stress_Score'])

In [9]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 4454 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4454 non-null   str
 1   Age                          4454 non-null   int64
 2   Gender                       4454 non-null   str
 3   Academic_Level               4454 non-null   str
 4   Primary_Platform             4454 non-null   str
 5   Daily_Usage_Hours            4454 non-null   float64
 6   Weekend_Extra_Hours          4454 non-null   float64
 7   Device_Type                  4454 non-null   str
 8   Sleep_Duration_Hours         4454 non-null   float64
 9   Sleep_Quality_Score          4454 non-null   int64
 10  Late_Night_Usage             4454 non-null   bool
 11  Social_Comparison_Frequency  4454 non-null   str
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4454 non-null   int64
 14  Academic_Performance_GPA     4369 non-null   float64
 15  Overall_Impact               4454 non-null   str
dtypes: bool(1), float64(5), int64(3), str(7)
memory usage: 561.1 KB

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['Weekley_Usage_Hours'] = (df['Daily_Usage_Hours'] * 7) + (df['Weekend_Extra_Hours'] * 2 )

In [12]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,Weekley_Usage_Hours
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral,55.5
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,34.8
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral,79.7
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,46.6
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial,28.3

In [13]:
mean_usage_by_gender = df.groupby('Gender')['Weekley_Usage_Hours'].mean()
mean_usage_by_gender

Gender
Female               40.836079
Male                 40.411263
Non-Binary           41.345082
Prefer not to say    41.269892
Name: Weekley_Usage_Hours, dtype: float64

In [14]:
df_noid = df.drop(columns=['Student_ID'])

In [15]:
df_noid.head()

,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact,Weekley_Usage_Hours
0,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral,55.5
1,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial,34.8
2,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral,79.7
3,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial,46.6
4,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial,28.3

1. skapa en ny kolumn med uträknad data
2. leta efter felvärden (ingen värde eller null) och antingen ta bort rader eller lägga in värden
3. förbered för ML plocka bort irelevanta kolumner